Added CVE Information
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #62
Opened 2019-10-23 16:53 UTC by ethandellaposta

2019-10-30 15:07 UTC, yerngpaii requested changes

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      notroj had to rewrite the ap_resolve_env function to avoid buffer overflow. The rewritten function
who/what is notroj?

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      beyond this to avoid obverflow. It also casts the ap_resolve_env function to (char *).
overflow *

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      Orginial commit of the ap_resolve_env function that claims that the change for handling ${ENV} constructs
Original *

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      Orginial commit of the ap_resolve_env function that claims that the change for handling ${ENV} constructs
You could also just write environments instead of ${ENV}

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
>    contest:
Fill these in ?

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      note: Lots of minor syntax and function parametewr changes. Claims to fix command initialisation.
parameter *

2019-10-30 15:07 UTC, yerngpaii commented on cves/CVE-2004-0747.yml
> +      and subsequent gain of privledges.
privileges *

2019-11-01 13:30 UTC, Mirldog reviewed
A couple minor things, but looks good overall!

2019-11-01 13:30 UTC, Mirldog commented on cves/CVE-2004-0747.yml
> +        unmodified
It might be helpful to expand on why this is interesting. Maybe elaborate on what that new feature was?

2019-11-01 13:30 UTC, Mirldog commented on cves/CVE-2004-0747.yml
> +    note: Environment variable expansion is what caused the buffer overflows, so this applies.
Just a formatting tweak, no need to say 'so this applies' when you say 'applies: true' right above it

2019-11-01 14:55 UTC, ethandellaposta commented on cves/CVE-2004-0747.yml
> +      notroj had to rewrite the ap_resolve_env function to avoid buffer overflow. The rewritten function
Github user for httpd, I'll modify this.

2019-11-01 14:57 UTC, ethandellaposta commented on cves/CVE-2004-0747.yml
> +      Orginial commit of the ap_resolve_env function that claims that the change for handling ${ENV} constructs
I'll make that change.

2019-11-01 15:01 UTC, ethandellaposta commented on cves/CVE-2004-0747.yml
> +        unmodified
That's a good point. I could a little more contextual information about this change but the main point was that it was used as part of a new feature and wasn't modified, solidifying the probability that the fix was a good one. I'll add this to my commit.

2019-11-01 15:02 UTC, ethandellaposta commented on cves/CVE-2004-0747.yml
> +    note: Environment variable expansion is what caused the buffer overflows, so this applies.
You're right 👍

2019-11-01 16:28 UTC, yerngpaii commented
I give this 3 upvotes

2019-11-01 16:28 UTC, yerngpaii approved these changes

2020-02-27 19:30 UTC, merged