CVE-2014-3581
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #65
Opened 2019-10-24 03:08 UTC by yerngpaii

updated yml file answering questions

2019-10-31 00:21 UTC, Ramenous requested changes
For the lessons section:
I think this vulnerability applies to two of these lessons:
1. Denial of service: since the description describes this vulnerability as a denial of service due to attackers being able to crash the application with empty content type headers
2. Distrust Input: since the application doesn't check if the content type headers are empty, that allows attackers to be able to supply empty content type headers and crash the application.

Overall, this is an interesting vulnerability because I've never heard of using empty headers to crash an application: +5 points!!

2019-10-31 00:21 UTC, Ramenous commented on cves/CVE-2014-3581.yml
>  vccs:
There seems to be no vccs for this vulnerability. Not sure if it was missed or intentionally left empty, but a note or some kind should be provided as this is pretty important.

2019-10-31 20:45 UTC, yerngpaii commented on cves/CVE-2014-3581.yml
>  vccs:
noted and added the vcc, it took a while to find. The commit was made in 2008 while the fix was implemented in 2014

2019-10-31 20:46 UTC, yerngpaii commented
@Ramenous changes were made, can you please review this again for anything I may have missed?

2019-11-01 01:01 UTC, Ramenous commented
> @Ramenous changes were made, can you please review this again for anything I may have missed?

I think you're good with this.

2019-11-01 14:14 UTC, CraftSpider reviewed
I generally don't have comments, but I marked two sentences for readability

2019-11-01 14:14 UTC, CraftSpider commented on cves/CVE-2014-3581.yml
> +  and lead to a denial of service attack if attackers would supplied an empty Content-Type
```suggestion
  and lead to a denial of service attack if attackers supplied an empty Content-Type 
```

2019-11-01 14:14 UTC, CraftSpider commented on cves/CVE-2014-3581.yml
> +  header, since it would be a NULL pointer dereference and leads to application crash.
```suggestion
  header, since it would be a NULL pointer dereference and lead to an application crash.
```

2019-11-01 20:49 UTC, Ramenous approved these changes

2020-02-20 18:09 UTC, merged