CVE 2014-3583
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #66
Opened 2019-10-24 18:20 UTC by exl5325

Added curated data for CVE 2014-3583.

Completed: 

- CWE
- Curated
- Reported Date
- Announced Date
- Published Date
- Description
- Bounty
     - Apache does not offer bounties for bugs or vulnerabilities
- Reviews
- Repo
- Fix/VCC
- Discovered
- Subsystem
- Interesting commits
- Major events (n/a)
- Lessons
- Mistakes
- Unit test
- Bug number (n/a)
    - Apache separates bug reports and security issues. Vulnerabilites are separate from bug reports, and therefore aren't assigned a bug number.

2019-10-28 22:39 UTC, Ozay34 requested changes
Overall, this was very easy to read and gave a clear description of the issue.

2019-10-28 22:39 UTC, Ozay34 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
These two paragraphs seem like they would read better if they were joined.  For example, the sentence "could send a carefully crafted response" doesn't make much sense without "is sent a long HTTP header."

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
FastCGI is also a bit confusing, is that a different HTTP server? something entirely different? Just a quick sentence giving an overview as to what it is might be useful.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
Otherwise, great job with the second half, your description is very clear and concise.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    security issues in HTTPD.
Was he working for anyone in particular or was this just a personal project?

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    auth & authorization. The path name is 'aaa', which also stands for authentication
Auth can usually be confused between authorization and authentication, although it is immediately followed by authorization, spelling it out here might be more clear.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +  name: Authentication and Authorization
Why is the vulnerability in this module, was it specific to long auth headers, or did this module control all headers for security purposes? Maybe some more information to include somewhere.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    note: Vulnerability was caused by trusting that external input already contained a null char '\0'.
This would also be good to include in the description (about the null char) to add some more clarity.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    mechanism that stops C from reading memory past the end of the string.
Is the null character even part of the HTTP standard? I was under the assumption that a newline was what delimited different headers.  If it isn't it seems like a massive oversight on Apache's part.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    appears on headers over a certain length.
With the addition of new standards every day (especially years ago) the need for header length is growing larger and larger, if Apache had limited the size of the headers, would they have run into issues with support for newer standards? If so, would there be a better way to fix this?

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    appears on headers over a certain length.
I may be biased, but it seems to me that this is a design flaw, if this is an issue in this specific module, how may other modules are also parsing HTTP request headers themselves, wouldn't it be better for there to be a module dedicated to parsing requests to turn the untrusted input into a trusted form?  I agree that at the face of it, this was a simple coding mistake, but some coding mistakes can be prevented with a solid design.

2019-10-28 22:39 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    outside input and placed checks to prevent memory from being read
Great description of how this vulnerability applies to C, would this be something that other languages should be careful of as well?

2019-10-29 00:11 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +    outside input and placed checks to prevent memory from being read
Strings in higher level languages don't require a null terminator because you will not be allowed to search out of bounds - for ex, the JVM will throw an `OutOfBounds` Exception if you attempt go off the end of a string. Since C gives you 100% control of memory, it doesn't care if you attempt to read off the end of your string, which is why you need the null char to specifically let the language know where the end of the string is.

2019-10-29 00:33 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +    security issues in HTTPD.
Based off what I found he seems to just be an individual who does this kind of work as a personal project

2019-10-29 00:36 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
> These two paragraphs seem like they would read better if they were joined. For example, the sentence "could send a carefully crafted response" doesn't make much sense without "is sent a long HTTP header."

First paragraph was a copy-paste from the security report on Apache's website, second paragraph was my own commentary. I'll add the details about what FastCGI is though.

2019-10-29 00:43 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
I thought it sounded like it was copied and pasted, but I didn't see it after some very brief looking around.  The reason I mentioned that was because I felt like I had to take a massive step back after reading the first paragraph so that the second could fill me in, is the first one even needed?

2019-10-29 00:45 UTC, adw4236 commented on cves/CVE-2014-3583.yml
> +    outside input and placed checks to prevent memory from being read
Yeah, I was just wondering if that might be something worth putting in there that this is really only applicable to C, but it may not be needed.

2019-10-29 00:51 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +  issues due to the potential for segmentation faults from buffer overflow.
Fair point, I figured it might be a useful reference. I'll just add a "Apache Description" label to clarify it

2019-10-29 01:27 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +  name: Authentication and Authorization
Not exactly sure why. It looks like this module handles FastCGI authentication specifically, but it wouldn't explain why (like you mentioned) they wouldn't just handle headers in one uniform place

2019-10-29 01:27 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +    appears on headers over a certain length.
> how may other modules are also parsing HTTP request headers themselves, wouldn't it be better for there to be a module dedicated to parsing requests to turn the untrusted input into a trusted form

I think this is a really good point and I'll add it into the YAML.

2019-10-29 01:41 UTC, exl5325 commented on cves/CVE-2014-3583.yml
> +    mechanism that stops C from reading memory past the end of the string.
Not entirely sure what the under-the-hood mechanisms are to get information from servers into memory. I'll try to look into it to see if I can find anything

2020-02-20 18:08 UTC, merged