CVE-2016-8740
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #69
Opened 2019-10-24 23:11 UTC by 17mgeffert

httpd issue with denial of service

2019-10-28 03:16 UTC, mesternefeld commented on cves/CVE-2016-8740.yml
> +  The mod_http2 module in the Apache HTTP Server 2.4.17 through 2.4.23, when the Protocols configuration includes h2 or h2c, does not restrict request-header length, which allows remote attackers to
I'm a little confused with what this is. It should be the CWE of the CVE. Commonly in the format CWE-400 or just simply 400

2019-10-31 20:59 UTC, mev1482 requested changes

2019-10-31 20:59 UTC, mev1482 commented on cves/CVE-2016-8740.yml
> +  from being able to use it.
Is a denial of service attack could be accomplished? May want to state that explicitly if that is the case.

2019-10-31 20:59 UTC, mev1482 commented on cves/CVE-2016-8740.yml
> +      git-svn-id https://svn.apache.org/repos/asf/httpd/httpd/trunk@1744415 13f79535-47bb-0310-9956-ffa450edef68"
May want to break up text into more lines.

2019-10-31 20:59 UTC, mev1482 commented on cves/CVE-2016-8740.yml
> +    false
Capitalize this. False should be same line not new line

2019-10-31 20:59 UTC, mev1482 commented on cves/CVE-2016-8740.yml
> +    issue.
Beyond testing they might have implemented better design to check input size. I agree that unit testing and QA would have helped to find the problem after its injection into the system.

2019-10-31 22:44 UTC, 17mgeffert commented on cves/CVE-2016-8740.yml
> +  from being able to use it.
good idea, ill be sure to include it

2019-10-31 22:48 UTC, 17mgeffert commented on cves/CVE-2016-8740.yml
> +    false
just for consistency, I like to keep all text on new line, in addition, as false it technically not a string, but really a boolean, i think lowercase false is fine.

2019-10-31 22:48 UTC, 17mgeffert commented on cves/CVE-2016-8740.yml
> +    issue.
good catch

2020-02-20 18:06 UTC, merged