CVE-2004-0809
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #84
Opened 2019-10-25 08:30 UTC by Jonathan-Eid

2019-10-26 00:30 UTC, Jonathan-Eid commented
I think the master branch pull request was mistake, this is what I meant to merge in. Can you see my finished yml file?

2019-10-30 15:34 UTC, yerngpaii commented
continue of #60

2019-10-30 15:38 UTC, yerngpaii requested changes

2019-10-30 15:38 UTC, yerngpaii commented on cves/CVE-2004-0809.yml
> +    Once the WebDAV undergoes an indirect lock, the wrong memory address is accessed and it results in a segmentation
What is WebDAV and how does it relate to the HTTPD ?

2019-10-30 15:38 UTC, yerngpaii commented on cves/CVE-2004-0809.yml
> +  answer: There isn't a lot of information but the vulnerability was found by a consistant maintainer of the project.
consistent *

2019-10-30 15:38 UTC, yerngpaii commented on cves/CVE-2004-0809.yml
> +  answer: There isn't a lot of information but the vulnerability was found by a consistant maintainer of the project.
Who is this consistent maintainer ?

2019-10-30 15:38 UTC, yerngpaii commented on cves/CVE-2004-0809.yml
> +  answer: An extension of HTTPD that handles collaboratively editting files on web servers, specifically the locking part
collaborative * editing * [of]

2019-10-30 15:38 UTC, yerngpaii commented on cves/CVE-2004-0809.yml
> +      note:  It seems like the way locking was designed in this system has been very problamatic for quite some time
problematic *

2019-11-01 11:50 UTC, JoshVerDow commented on cves/CVE-2004-0809.yml
>    find this in changelogs, blogs, bug reports, or perhaps the CVE date. A good
Announced date should be in YYYY-MM-DD format for readability (remove T04:00Z).

2019-11-01 11:53 UTC, JoshVerDow commented on cves/CVE-2004-0809.yml
> +      note:  It seems like the way locking was designed in this system has been very problamatic for quite some time
The note for this interesting commit does not really illustrate why it was interesting.  A little more explanation as to the contents of the commit would help for ease of information access.

2019-11-01 11:58 UTC, JoshVerDow commented on cves/CVE-2004-0809.yml
> +      The fix presented did make it seem like a coding mistake as I interpret their was a typo causing the wrong memory address to be altered. But looking further in the commits
This first sentence is kind of hard to read.  I would suggest, "The fix presented made it seem like the problem was a coding mistake.  There was a typo causing the wrong memory address to be altered."

2019-11-01 12:02 UTC, JoshVerDow commented on cves/CVE-2004-0809.yml
> +      I realize the whole way the system was designed had a lot of faults so there definitely was some design flaws with the way locking worked.
If you found more examples of design faults, maybe add an example for reference?

2019-11-01 12:58 UTC, JoshVerDow commented on cves/CVE-2004-0809.yml
>    vulnerability, fill it out here. Or correct it if the information already here
I'd like to add 2 upvotes.

2020-02-06 19:21 UTC, merged