CVE-2014-0231
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #86
Opened 2019-10-25 10:58 UTC by etiano417

- Filled yml fields for CVE-2014-0231
 - replaced incorrect fix commits with accurate ones for CVE-2014-0231

2019-10-31 12:19 UTC, heartemoji commented on cves/CVE-2014-0231.yml
> +      Because the vulnerability is caused by a lack of measure against halting,
Run on sentence, breaking it up into two parts might help readability.

2019-10-31 12:22 UTC, heartemoji commented on cves/CVE-2014-0231.yml
> +      to halt)
I think that having a full sentence and a little more detail here would be important for the CWE.

2019-10-31 12:23 UTC, heartemoji commented on cves/CVE-2014-0231.yml
> +      impact of certain inputs
Lacking a subject of the sentence here, again perhaps a little more detail and a full sentence would add more value to the CVE

2019-10-31 12:24 UTC, heartemoji commented on cves/CVE-2014-0231.yml
> +    fail gracefully. The issue - the process responsivle for running CGI scripts
Small spelling error here on "responsive"

2019-10-31 12:26 UTC, heartemoji commented
Overall, well done in my opinion. I give this CVE 2 upvotes. (I would give more but I was not careful and gave two many away already).

2019-11-01 03:03 UTC, etiano417 commented
Fixed issues noted by @heartemoji (see the previous commit)

2019-11-01 11:28 UTC, ghost requested changes

2019-11-01 11:28 UTC, ghost commented on cves/CVE-2014-0231.yml
> +    HTTP Server has a module "mod_cgid" which is responsible for runnig CGI
Typo: runnig -> running

2019-11-01 11:28 UTC, ghost commented on cves/CVE-2014-0231.yml
> +      proper measures against halting from its introduction).
I would use the same wording from the description. You could say that the component lacked command timeout from its introduction instead.

2019-11-01 11:28 UTC, ghost commented on cves/CVE-2014-0231.yml
> +    vulnerability on June 16th 2014 and reported it to the Apache Security Team.
Did he say how he discovered it?

2019-11-01 11:28 UTC, iclare commented on cves/CVE-2014-0231.yml
> +      without halting on all conditions.
In this case, aren't CGI script writers users of the system? From the perspective of the contributors to httpd, isn't the input just a script that runs for some unknown amount of time? This should be written from the perspective of httpd's contributors.

2019-11-01 11:28 UTC, iclare commented on cves/CVE-2014-0231.yml
> +        timeouts are a layer of robustness underneath normal CGI input validation
Missing capitalization and a period.

2019-11-01 11:28 UTC, iclare commented on cves/CVE-2014-0231.yml
> +CWE: 754
CWE-754: Improper Check for Unusual or Exceptional Conditions

I would think that a non terminating script is something to be expected for a scriptable system.

I think CWE-400: Uncontrolled Resource Consumption might be better.

2019-11-01 12:03 UTC, iclare commented
1 upvote

2019-11-04 15:41 UTC, etiano417 commented on cves/CVE-2014-0231.yml
> +      proper measures against halting from its introduction).
Thanks for the recommendation! I'll definitely use this change of wording.

2019-11-04 15:42 UTC, etiano417 commented on cves/CVE-2014-0231.yml
> +CWE: 754
good catch! I think that is more appropriate, thank you.

2020-02-06 16:43 UTC, merged