CVE-2004-0748
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #89
Opened 2019-10-25 15:23 UTC by jennaMac

edited CVE-2004-0748.yml

2019-10-28 02:45 UTC, mesternefeld commented on cves/CVE-2004-0748.yml
>    integrity checks on this file to make sure you fill everything out properly.
Please fill in the CWE above to fix the CI

2019-10-28 19:22 UTC, etiano417 requested changes
The wording of the description is a bit confusing. currently, it seems to imply that there was a denial of service attack which would lead to an entirely separate consumption of resources. Since it is the consumption of CPU resources that leads to the denial of service, you may want to rearrange the ordering of the phrase "Remote attackers were able to cause a denial of service, which consumed CPU" to something like "Remote attackers were able to consume CPU resources, which lead to a denial of service," or else to specify that attackers could "perform a denial of service _attack_, which _involved_ consuming CPU resources" to be clearer.

It would also be helpful to write something about  how the attacker can go from a denial of service attack to an escalation of privileges - from the current vulnerability description, it is not clear how
this can happen.

2019-11-01 11:29 UTC, ghost requested changes

2019-11-01 11:29 UTC, iclare commented on cves/CVE-2004-0748.yml
> +description: Remote attackers were able to cause a denial of service, which consumed CPU in version up to 2.0.50 in mod_ssl.  They did this by aborting SSL connections in a way that cause an infinite
This is a higher level description, so it would be better to leave out version references.

What are SSL connections? Does the denial of service come first or the privilege escalation; or are they mutual?

2019-11-01 11:29 UTC, iclare commented on cves/CVE-2004-0748.yml
> +  answer: This vulnerability came from coding mistakes and then maintainability mistakes prevented a quick fix.  They ended up just removing the code in order to get rif of the issue in an update.
How does this relate to the applicable lessons?

2019-11-01 14:20 UTC, etiano417 commented
I would like to give 1 upvote to this vulnerability

2019-11-01 18:04 UTC, sxm7571 commented on cves/CVE-2004-0748.yml
> +  answer: https://bugzilla.redhat.com/show_bug.cgi?id=130750   https://lists.apache.org/thread.html/54a42d4b01968df1117cea77fc53d6beb931c0e05936ad02af93e9ac@%3Ccvs.httpd.apache.org%3E
It might be helpful to leave some sort of summary here of the information from this link. Then leave the link here as well if someone wants to link into it more.

2019-11-01 18:09 UTC, sxm7571 commented on cves/CVE-2004-0748.yml
> +  answer: This vulnerability came from coding mistakes and then maintainability mistakes prevented a quick fix.  They ended up just removing the code in order to get rif of the issue in an update.
You may try to tie the CWE into this. Does the fix for this vulnerability align with the mitigation for the CWE?

2022-09-30 18:37 UTC, closed without merging