CVE-2013-1896
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #93
Opened 2019-10-26 17:51 UTC by adw4236

2019-10-26 20:37 UTC, exl5325 requested changes

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +  resources or documents.  One place WebDAV is used is in version controll over
nit: controll -> control

Another really good description here

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +  code: false
You mentioned that no unit tests were made for the fix, was there a unit test run when the feature was initially developed?

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +    modification of files over HTTP like with the use of version controll.
nit: controll -> control

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +    fairly likely that similar vulnerabilities exist in this module because most
Good observation

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +      sanatized, or filtered to ensure that only real requests are made.
You should also mention that servers should check for non-native HTTP requests (like those part of WebDAV) and find a way to handle such requests

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +    placed in the wrong function, overall, this is an architectural design mistake.
Agreed

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +      Version controll is a very complex system with many different ways to interact.
Control is spelled incorrectly again

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +    The vulnerability was discovered and a fix was proposed (and accepted) by
Maybe some clarification could bse useful here. Right now, it sounds like the same guy who discovered the fix also wrote the fix and then accepted his own fix(?) Probably not the case, but that's how the sentence reads.

2019-10-26 20:37 UTC, exl5325 commented on cves/CVE-2013-1896.yml
> +      There are multiple layers of security when it comes to http requests,
This sounds like something that should go in `distrust input` rather than `defense in depth`

2019-10-29 00:22 UTC, adw4236 commented on cves/CVE-2013-1896.yml
> +      There are multiple layers of security when it comes to http requests,
I think it applies to both here, although it is true that you should not trust the input from an HTTP request, you should also provide multiple layers of security when validating an HTTP request so there are multiple walls to block potentially harmful input like what we see in this vulnerability.

2019-10-29 00:26 UTC, adw4236 commented on cves/CVE-2013-1896.yml
> +  code: false
Added a bit of clarification

2019-10-29 00:27 UTC, adw4236 commented on cves/CVE-2013-1896.yml
> +      sanatized, or filtered to ensure that only real requests are made.
Added a bit more about non-native HTTP requests

2019-10-29 00:27 UTC, adw4236 commented on cves/CVE-2013-1896.yml
> +    The vulnerability was discovered and a fix was proposed (and accepted) by
Reworded to make this less confusing

2020-02-06 16:42 UTC, merged