CVE-2009-1891
VulnerabilityHistoryProject/httpd-vulnerabilities pull request #99
Opened 2019-11-01 15:41 UTC by MaeveMonster

modified yml file for CVE-2009-1891

2019-11-01 21:33 UTC, Ramenous requested changes
For lessons learned, I think you could add denial of service to this since the vulnerability is what caused denial of service attacks from the continuation of compression of large files

2019-11-01 21:33 UTC, Ramenous commented on cves/CVE-2009-1891.yml
>    automated:
If the vulnerability was found by a user then automated, google, and contest should be false (true for contest if there was an actual contest for this)

2019-11-01 21:33 UTC, Ramenous commented on cves/CVE-2009-1891.yml
>  major_events:
There doesn't seem to be any major events between vccs and fix which is fine, but I think you should provide a summary or brief explanation of what was going on so that readers can grasp the type of development happening during this time that may or may not have affected the vulnerability and its solution

2019-11-04 00:49 UTC, MaeveMonster commented on cves/CVE-2009-1891.yml
>  major_events:
I couldn't really find a description of what the developers were dealing with while writing this fix.

2019-11-06 18:26 UTC, Ramenous approved these changes

2022-09-30 18:37 UTC, closed without merging